#pragma once

#include "GemmaStage.h"

#include "llama.h"
#include "ggml.h"
#include "ggml-backend.h"
#include "mtmd.h"
#include "mtmd-helper.h"
#include "chat.h"
#include "sampling.h"

#include <algorithm>
#include <atomic>
#include <cctype>
#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <mutex>
#include <string>
#include <vector>

struct GS_EngineSettings {
    std::string model_path;
    std::string mmproj_path;
    std::string backend;
    int         n_ctx = 0;
    int         n_gpu_layers = -1;
    bool        benchmark = false;
};

struct GS_Engine {
    llama_model*  model = nullptr;
    mtmd_context* mtmd = nullptr;
    std::string   backend_name;
    bool          benchmark = false;
    bool          gpu_enabled = false;
    uint32_t      n_ctx = 0;
};

struct GS_ConversationConfig {
    std::string system_message;
    std::string tools_json;
    bool        constrained_decoding = false;
    bool        retain_text_only_media_history = false;
    bool        enable_thinking = true;
    // 0 = inherit GS_Engine::n_ctx. Anything > 0 overrides the per-conversation
    // KV cache size, useful for short-lived single-purpose conversations (e.g.
    // ASR per-chunk) that would otherwise allocate the full engine window.
    int         n_ctx_override = 0;
};

struct GS_ChatMessage {
    std::string role;
    std::string content;
    enum class MediaKind {
        None,
        Audio,
        Image,
    };
    MediaKind            media_kind = MediaKind::None;
    std::vector<uint8_t> media_bytes;
    // Multimodal turns are now replayed from cached decoded bitmaps instead of
    // re-decoding the original file bytes every turn.
    mtmd::bitmap         media_bitmap;
};

struct GS_BenchmarkInfo {
    double ttft = 0.0;
    double prefill_tok_per_s = 0.0;
    double decode_tok_per_s = 0.0;
    int    prefill_tokens = 0;
    int    decode_tokens = 0;
    double commit_overhead_s = 0.0;
    int    commit_tokens = 0;
    // Wall time spent rendering the built-in chat template. On the fast path
    // this is only a constant-size probe render for the newest turn; fallback
    // paths may still rebuild full history for safety.
    double phase_template_build_s = 0.0;
    // Wall time spent in the prefill helper (tokenize + mtmd encode +
    // llama_decode of the delta), separating pure prefill cost from the
    // template/sampler setup above.
    double phase_prefill_s = 0.0;
};

struct GS_Conversation {
    GS_Engine*                    engine = nullptr;
    llama_context*                ctx = nullptr;
    common_sampler*               sampler = nullptr;
    GS_ConversationConfig         config;
    std::atomic<bool>             cancel_flag{false};
    int32_t                       n_past = 0;
    std::vector<GS_ChatMessage>   chat_history;
    // Authoritative snapshot of what should already exist in KV. New turns try
    // to append only the rendered prompt delta beyond this string.
    std::string                   committed_prompt;
    // Number of media items already represented by committed_prompt/KV.
    size_t                        committed_bitmap_count = 0;
    // Verified assistant suffix from the real Jinja template. We only allow
    // text-delta reuse when the committed prompt ends on this proven boundary.
    std::string                   verified_prompt_suffix;
    // Verified prompt-locality flags. When true, we can render a constant-size
    // synthetic turn and splice its delta onto committed_prompt instead of
    // rebuilding the full history prompt every turn.
    bool                          verified_incremental_text_turn = false;
    bool                          verified_incremental_media_turn = false;
    // Verified concat rules for the common plain-text assistant case:
    // committed_prompt_after = formatted + assistant_text + verified_suffix.
    bool                          verified_plain_text_commit_after_text_turn = false;
    bool                          verified_plain_text_commit_after_media_turn = false;
    std::vector<llama_token>      eot_suffix_tokens;
    llama_token                   tok_end_of_turn = -1;
    common_chat_templates_ptr     chat_templates;
    std::vector<common_chat_tool> parsed_tools;
    GS_BenchmarkInfo              last_benchmark;
};

struct GS_JsonResponse {
    std::string content;
};

struct GS_GenerationResult {
    std::string text;
    std::string json_body;
    int32_t     prompt_tokens = 0;
    int32_t     decode_tokens = 0;
    double      ttft_s = 0.0;
    double      decode_s = 0.0;
    bool        ok = false;
    bool        cancelled = false;
    // Set when we cannot trim generated bytes back to a clean token boundary,
    // so the next committed state must be rebuilt conservatively.
    bool        needs_kv_resync = false;
};

enum class GS_BackendPreference {
    Auto,
    CUDA,
    Vulkan,
    CPU,
};

struct GS_BackendSelection {
    ggml_backend_dev_t   device = nullptr;
    GS_BackendPreference preference = GS_BackendPreference::CPU;
    std::string          backend_name = "CPU";
    bool                 gpu_enabled = false;
};

extern std::atomic<int> g_min_log_level;
extern std::mutex       g_backend_runtime_mutex;
extern size_t           g_backend_runtime_refcount;

void gs_log(int level, const char* fmt, ...);
std::string NormalizePath(const char* path);
std::string ToLowerCopy(const std::string& value);
void gs_backend_runtime_acquire();
void gs_backend_runtime_release();
bool SelectBackend(const GS_EngineSettings& settings, GS_BackendSelection* selection);

GS_JsonResponse* gs_build_turn_response(const GS_GenerationResult& result);

GS_GenerationResult gs_run_user_turn(
    GS_Conversation*          conversation,
    const std::string&        role,
    const std::string&        text,
    GS_StreamCallback         callback      = nullptr,
    void*                     callback_data = nullptr,
    GS_ChatMessage::MediaKind media_kind    = GS_ChatMessage::MediaKind::None,
    std::vector<uint8_t>      media_bytes   = {});
